constants:
  right_censoring_date: 1000
  critical_age: 20
  ratiomax: 10
estimations:
  mortality:
    expected_time_to_death: [0,1,21]
    survival_shape_parameter: [0,1,21]
    ratio_expected_time_to_death_male_vs_female: [0,1,21]
    probability_of_death_before_critical_time: [0,1,21]
    sex_ratio: [0,1,21]
  maturity:
    expected_time_to_maturity: [0,1,21]
    maturity_shape_parameter: [0,1,21]
    ratio_expected_time_to_maturity_male_vs_female: [0,1,21]
  reproduction:
    expected_time_next_reproduction: [0,1,21]
    reproduction_shape_parameter: [0,1,21]
    number_offspring_per_reproduction_or_fitness: [0,1,21]
    increase_in_death_hazard_following_a_reproduction_event (=tof): [0,1,21]
    tof_reduction_date: exponential_rate_of_decrease_of_tof_with_time: [0,1,21]
    increase_in_tof_proportional_to_number_of_offspring:
    (=tof_number_of_offspring): [0,1,21]
    linear_decrease_in_hazard_rate_with_time_since_maturity: [0,1,21]
    (=linear_senescence_of_interval_between_reproduction_events): [0,1,21]
    quadratic_senescence_of_interval_between_reproduction_events:
    quadratic_decrease_in_hazard_rate_with_time_since_maturity: [0,1,21]
    linear_change_in_number_of_offspring_with_time_since_maturity: [0,1,21]
    quadratic_change_in_number_of_offspring_with_time_since_maturity: [0,1,21]
    tof_between_previous_reproductive_interval_and_current_number_of_offspring: [0,1,21]
