---
mortality:
  expt_death: geno + type
  survival_shape: geno + type + geno*type
  ratio_expt_death: geno
  prob_death: geno
  sex_ratio: type
reproduction:
  expt_reproduction: not_fitted
  reproduction_shape: not_fitted
  n_offspring: not_fitted
  increase_death_hazard: not_fitted
  tof_reduction_date: not_fitted
  increase_tof_n_offspring: not_fitted
  lin_decrease_hazard: not_fitted
  quad_decrease_hazard: not_fitted
  lin_change_n_offspring: not_fitted
  quad_change_n_offspring: not_fitted
  tof_n_offspring: not_fitted
maturity:
  expt_maturity: geno + type
  maturity_shape: geno
  ratio_expt_maturity: geno + type