name: R Package Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    # Set up R environment and dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3" # You can specify the R version you want to use

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: remotes # Optional, add any extra R packages you need here

      # Run unit tests using `testthat`
      - name: Run tests
        run: |
          Rscript -e 'install.packages("testthat")'
          R CMD check --no-manual --as-cran
