name: Check pkgdown site works

on:
  pull_request:
    branches: [main]

jobs:
  deploy-pkgdown:
    runs-on: macos-latest

    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Check Quarto install
        run: |
          which quarto
          quarto check

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::pkgdown
            any::quarto
            any::DT
          cache: true

      - name: Build pkgdown site
        run: |
          Rscript -e 'devtools::install()'
          Rscript -e 'devtools::load_all()'
          Rscript -e 'devtools::build_site(quiet=FALSE)'
