name: Deploy pkgdown site

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-pkgdown:
    runs-on: macos-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          # Install common dependencies via Homebrew
          brew install curl openssl libxml2
          # Set environment variables for proper linking
          echo "PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "LDFLAGS=-L/opt/homebrew/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/opt/homebrew/include" >> $GITHUB_ENV

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::pkgdown
            any::quarto
            any::yaml
            any::glue
            any::tidyverse
            any::DT
          cache: true

      - name: Build pkgdown site
        run: |
          Rscript -e 'devtools::build_site(quiet=FALSE)'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
