name: R Package CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      R_VERSION: "4.4.1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R package dependencies
        run: |
          Rscript -e 'install.packages("devtools")'
          Rscript -e 'devtools::install_deps(dependencies = TRUE)'

      - name: Load the package in development mode and run tests
        run: |
          Rscript -e 'devtools::load_all(compile = FALSE)'
          Rscript -e 'devtools::test()'
