name: Windows - Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.1"

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: remotes,devtools,testthat

      - name: Run unit tests
        shell: pwsh # Use PowerShell for compatibility
        run: |
          Rscript -e "devtools::test()"
